Set `no-js` on HTML element and remove earlier
roots/sage pull request #2916
Opened 2021-12-29 22:31 UTC by knowler

Setting `no-js` on the `html` element seems a bit more common than on the `body`. Also, we can just use an inline script to remove the class early in `index.php`. Then since `@wordpress/dom-ready` should be available, we don’t need our own version of it included in the boilerplate. This means we aren’t providing the dev with it, but they can use whatever they want.

Breakdown of the changes in list form:

- Moves the `no-js` class to the `html` element.
- Remove the class early with a inlined script tag in the head.
- Use `@wordpress/dom-ready` in editor script.
- Remove our `domReady` utility.

2021-12-29 22:33 UTC, QWp6t approved these changes

2021-12-29 22:35 UTC, knowler commented
I have not tested this. The only thing I think which could go wrong is maybe needing to add WordPress’ `dom-ready` to the deps array for the editor script. I don’t know where that is though.

Also, adding the `no-js` removal inline script in `index.php` might be non-standard (as opposed to using `wp_head`), but I figure it’s close to where the class name is set on the element and therefore easier to see what it’s doing.

2021-12-29 23:01 UTC, knowler commented
Ok, I’ve tested this and it works. There’s no need to add any deps for the editor script since `wp-dom-ready` is in the window. I also just added a `js` class after the `no-js` one gets removed. Might be helpful and its in the link I referenced in the PR description. Not sure why PHP 7.3 is failing, but I think it was like that before.

2021-12-29 23:30 UTC, retlehs requested changes
could we keep a `domReady` example or starting point in `app.js`?

2021-12-29 23:32 UTC, retlehs commented
> Not sure why PHP 7.3 is failing, but I think it was like that before.

latest acorn release is triggering those failures rn, you can ignore (we're gonna just remove php 7.3 support)

2021-12-29 23:49 UTC, knowler commented
> could we keep a `domReady` example or starting point in `app.js`?

We can do that. We would need to add our `domReady` script back though.

2021-12-29 23:54 UTC, Log1x commented
> We can do that. We would need to add our domReady script back though.

I vote we add it back and keep it how it was outside of moving `no-js` to the `html` element.

2021-12-29 23:59 UTC, knowler commented
I added it back. Should we add it back to `editor.js` too? Or is using `@wordpress/dom-ready` there fine (since it’s already available in the admin).

2021-12-30 05:30 UTC, knowler commented
I changed directions here:

- This now removes the JS detection (see updated PR description for reasoning).
- It doesn’t change anything with the `domReady` stuff like it originally did.

2021-12-30 15:46 UTC, retlehs approved these changes

2022-01-02 20:12 UTC, merged